name: Sync to Hugging Face hub
on:
  push:
    branches: [main] # Chạy mỗi khi push vào nhánh main

  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout --orphan deploy-hf
          git add -A
          git commit -m "Deploy to HuggingFace"
          git push --force https://phanvanhieu:$HF_TOKEN@huggingface.co/spaces/phanvanhieu/3hchat deploy-hf:main
